"""add Board and Card models

Revision ID: 65d4b45fb47c
Revises: 6847dfe371c1
Create Date: 2024-12-23 13:32:22.746803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d4b45fb47c'
down_revision = '6847dfe371c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('likes_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('likes_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
